name: Build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-env:
    runs-on: ubuntu-latest
    steps:
      - name: Update variable in YML file
        run: |
          #YQ_VERSION="v4.43.1"
          #wget -q "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -O yq
          #chmod +x yq
          #sudo mv yq /usr/local/bin
          #echo $PATH
          yq --version
